x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile.airflow

  image: football-airflow:3.3.1

  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"

    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: >-
      postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@airflow-db:5432/airflow

    AIRFLOW__CORE__EXECUTION_API_SERVER_URL: >-
      http://airflow-api-server:8080/execution/

    AIRFLOW__API_AUTH__JWT_SECRET: ${AIRFLOW_JWT_SECRET}
    AIRFLOW__API__SECRET_KEY: ${AIRFLOW_API_SECRET_KEY}

    AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_USERS: >-
      ${AIRFLOW_ADMIN_USER}:admin

    FOOTBALL_DATA_API_TOKEN: ${FOOTBALL_DATA_API_TOKEN}

    DB_HOST: postgres
    DB_PORT: "5432"
    DB_NAME: ${DB_NAME}
    DB_USER: ${DB_USER}
    DB_PASSWORD: ${DB_PASSWORD}

    DBT_PROFILES_DIR: /opt/airflow/project/dbt_football
    PYTHONPATH: /opt/airflow/project


  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - airflow_logs:/opt/airflow/logs


services:

  postgres:
    image: postgres:17

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    ports:
      - "${POSTGRES_HOST_PORT}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5


  airflow-db:
    image: postgres:17

    environment:
      POSTGRES_DB: airflow
      POSTGRES_USER: ${AIRFLOW_DB_USER}
      POSTGRES_PASSWORD: ${AIRFLOW_DB_PASSWORD}

    volumes:
      - airflow_db_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${AIRFLOW_DB_USER} -d airflow"
        ]
      interval: 5s
      timeout: 5s
      retries: 5


  airflow-init:
    <<: *airflow-common

    depends_on:
      airflow-db:
        condition: service_healthy

    command:
      - bash
      - -c
      - airflow db migrate

    restart: "no"


  airflow-api-server:
    <<: *airflow-common

    command: api-server

    ports:
      - "8080:8080"

    depends_on:
      airflow-db:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully

    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--fail",
          "http://localhost:8080/api/v2/monitor/health"
        ]
      interval: 10s
      timeout: 5s
      retries: 10

    restart: unless-stopped


  airflow-scheduler:
    <<: *airflow-common

    command: scheduler

    depends_on:
      postgres:
        condition: service_healthy
      airflow-db:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully

    restart: unless-stopped


  airflow-dag-processor:
    <<: *airflow-common

    command: dag-processor

    depends_on:
      airflow-db:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully

    restart: unless-stopped


volumes:
  postgres_data:
  airflow_db_data:
  airflow_logs: